### ISSUE TITLE
Can't get it to work on 4.2.3.stable

### ISSUE THREAD

**Issue by electrical** [devopskube/redmine_openid_connect#60]
Hi,

I'm trying to make this work on Redmine 4.2.3.stable but so far I keep hitting the following error:

```
Started GET "/oic/login?utf8=%E2%9C%93&back_url=%2F&login-openid=Login+with+SSO" for 10.42.1.88 at 2022-01-12 19:45:06 +0000
--
Wed, Jan 12 2022 7:45:06 pm | Processing by AccountController#oic_login as HTML
Wed, Jan 12 2022 7:45:06 pm | Parameters: {"utf8"=>"✓", "back_url"=>"/", "login-openid"=>"Login with SSO"}
Wed, Jan 12 2022 7:45:06 pm | Current user: anonymous
Wed, Jan 12 2022 7:45:06 pm | Completed 500 Internal Server Error in 50ms (ActiveRecord: 4.6ms)
Wed, Jan 12 2022 7:45:06 pm |  
Wed, Jan 12 2022 7:45:06 pm | NoMethodError (undefined method `+' for nil:NilClass):
Wed, Jan 12 2022 7:45:06 pm |  
Wed, Jan 12 2022 7:45:06 pm | plugins/redmine_openid_connect/app/models/oic_session.rb:187:in `authorization_url'
Wed, Jan 12 2022 7:45:06 pm | plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:49:in `oic_login'
Wed, Jan 12 2022 7:45:06 pm | lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

The config is in the right place and has the right details.
My best guess is that the config fetching part doesn't work anymore. Although i used to have it working on 4.2.0

Any ideas?

**Comment by electrical** [comment]
After a restart of the redmine container it seems to be suddenly working fine. Very unexpected.

**Comment by JOSAML** [comment]
Hi,

I've the vzey same problem as previously posted.
Unfortunately despite a restart of my redmine container I can't make it work porperly
Any Idea to help me ?

Redmine-5.0.2 in a container, version 4.2.3 stable set up

> I, [2023-10-30T13:56:50.644401 #1]  INFO -- : Started GET "/oic/login?utf8=%E2%9C%93&login-openid=Login+with+SSO" for 172.20.0.1 at 2023-10-30 13:56:50 +0000
I, [2023-10-30T13:56:50.645307 #1]  INFO -- : Processing by AccountController#oic_login as HTML
I, [2023-10-30T13:56:50.645385 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "login-openid"=>"Login with SSO"}
I, [2023-10-30T13:56:50.649191 #1]  INFO -- :   Current user: anonymous
I, [2023-10-30T13:56:50.704453 #1]  INFO -- : Completed 500 Internal Server Error in 59ms (ActiveRecord: 9.0ms | Allocations: 5387)
F, [2023-10-30T13:56:50.715273 #1] FATAL -- :   
NoMethodError (undefined method `+' for nil:NilClass
    config["authorization_endpoint"] + "?" + authorization_query.to_param
                                     ^):
plugins/redmine_openid_connect/app/models/oic_session.rb:187:in `authorization_url'
plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:49:in `oic_login'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by desto12** [comment]
> Hi,
> 
> I've the vzey same problem as previously posted. Unfortunately despite a restart of my redmine container I can't make it work porperly Any Idea to help me ?
> 
> Redmine-5.0.2 in a container, version 4.2.3 stable set up
> 
> > I, [2023-10-30T13:56:50.644401 #1]  INFO -- : Started GET "/oic/login?utf8=%E2%9C%93&login-openid=Login+with+SSO" for 172.20.0.1 at 2023-10-30 13:56:50 +0000
> > I, [2023-10-30T13:56:50.645307 #1]  INFO -- : Processing by AccountController#oic_login as HTML
> > I, [2023-10-30T13:56:50.645385 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "login-openid"=>"Login with SSO"}
> > I, [2023-10-30T13:56:50.649191 #1]  INFO -- :   Current user: anonymous
> > I, [2023-10-30T13:56:50.704453 #1]  INFO -- : Completed 500 Internal Server Error in 59ms (ActiveRecord: 9.0ms | Allocations: 5387)
> > F, [2023-10-30T13:56:50.715273 #1] FATAL -- :
> > NoMethodError (undefined method `+' for nil:NilClass     config["authorization_endpoint"] + "?" + authorization_query.to_param                                      ^): plugins/redmine_openid_connect/app/models/oic_session.rb:187:in `authorization_url'
> > plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:49:in `oic_login' lib/redmine/sudo_mode.rb:61:in `sudo_mode'

I have the same problem, redmine 5.1.0 :(
