### ISSUE TITLE
Does it support redmine 5.x?

### ISSUE THREAD

**Issue by ok2uec** [devopskube/redmine_openid_connect#98]
Hello, 

does this plugin also support redmine 5.x ? 

The redmine website only supports version 3.4: 
https://www.redmine.org/plugins/redmine_openid_connect

**Comment by orzel** [comment]
Apparently no, it has not been updated for long, and i got an error while installing dependencies:

docker-redminetest-1  | An error occurred while installing bigdecimal (3.1.8), and Bundler cannot
docker-redminetest-1  | continue.
docker-redminetest-1  | 
docker-redminetest-1  | In Gemfile:
docker-redminetest-1  |   httparty was resolved to 0.14.0, which depends on
docker-redminetest-1  |     multi_xml was resolved to 0.7.1, which depends on
docker-redminetest-1  |       bigdecimal

**Comment by jcasals** [comment]
> Hello,
> 
> does this plugin also support redmine 5.x ?
> 
> The redmine website only supports version 3.4: https://www.redmine.org/plugins/redmine_openid_connect

Hey, just in case you didn't find a way to make it work, I was able to use redmine 5.1.4 (it didn't work with 5.1.5) by creating a Dockerfile with the following content
```
FROM redmine:5.1.4

RUN apt-get -y update
RUN apt-get -y install build-essential
```

Then building the image with a custom tag
```
docker build -t redmine:5.1.4-pic . 
```

And then installing redmine using docker normally with this image. With the last version of the plugin that is in this repository it worked. 

For some reason, there is an error showing up regarding the mysql2 adapter in the last 5.X version (5.1.5) and in 6.0.2. Since I was using 4.1.1, 5.1.4 is fine for me for the moment. 

Cheers,

Jordi

**Comment by tacerus** [comment]
Hi,

we use this with Redmine 5 with no issues. I patched the Gemfile to allow for httparty 0.22.0 to ease the dependencies, it does not seem to cause any issues.

**Comment by guwq-dave** [comment]
I wanted to add on to this-

This also works with 6.0.5, albeit I had to fix the code. Specifically, I was getting an error:

**NoMethodError (undefined method `negative?' for an instance of String):**

I had to edit my **..plugins/redmine_openid_connect/app/models/oic_session.rb** file by replacing the following line:

OLD: expiry = client_config['dynamic_config_expiry'] || 86400
NEW: expiry = (client_config['dynamic_config_expiry'] || 86400).to_i

It looks like the 86400 was getting returned as a string, rather than an integer. Hopefully this helps someone else out there.

**Comment by tacerus** [comment]
Hi @guwq-dave, is it actually defaulting to `86400` or is it defaulting to `0`? I had the error you mention when `dynamic_config_expiry` was not set (which actually means it was set to an empty string, causing the `|| 86400` to never be evaluated). Calling `to_i` on an empty string will yield 0, so the change might not have the desired result for everyone.

**Comment by arut-plus** [comment]
Thanks, @guwq-dave, this patch worked for me ❤️

**Comment by artlog** [comment]
As of today, patch is still required and worked well.
